theme: jekyll-theme-slate
locale                   : "en-US"
title                    : "Oceane Fourquet"
title_separator          : "-"
name                     : &name "Oceane Fourquet"
description              : &description "PhD Student at Institut Pasteur and LIP6"
url                      : https://ofourquet.github.io 
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "oceanefrqt/ofourquet.github.io"
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false 
words_per_minute         : 160
future                   : true
read_more                : "disabled" 
talkmap_link             : false 
